# Generated by Django 4.2.6 on 2023-11-16 07:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import school.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=350, unique=True, verbose_name='Course name')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Title')),
                ('body', models.TextField(verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Title')),
                ('body', models.TextField(verbose_name='body')),
                ('file', models.FileField(upload_to='Practice/', validators=[school.validators.validate_file_extension], verbose_name='file')),
                ('Submission_deadline', models.DateField(verbose_name='Submission deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=350, unique=True, verbose_name='School name')),
                ('address', models.TextField(verbose_name='School address')),
                ('location', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='body')),
                ('file', models.FileField(upload_to='Practice/', validators=[school.validators.validate_file_extension], verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.practice', verbose_name='practice')),
            ],
        ),
    ]
