# Generated by Django 4.2.6 on 2023-11-17 07:40

from django.db import migrations, models
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Practice/', validators=[school.validators.validate_file_extension], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='practiceresponse',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Practice/response/', validators=[school.validators.validate_file_extension], verbose_name='file'),
        ),
    ]
